### POST performanceId, startime, endtime and popularity to performanceWithPopularity table(OK)
@url1 = http://localhost:3000/advance/insert/
@url2 = http://localhost:3000/advance/result/
@httpMethod1 = POST
@httpMethod2 = GET

### POST data into performanceWithPopularity Table.(OK)
{{httpMethod1}} {{url1}} HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "festivalId": 2234567891, 
            "performanceId": 1234567890,
            "startTime": 1330,
            "endTime": 1330,
            "popularity": 1
        },
        {
            "festivalId": 2234567891,
            "performanceId": 1234567891,
            "startTime": 1330,
            "endTime": 1330,
            "popularity": 10
        },
        {
            "festivalId": 2234567891,
            "performanceId": 1234567892,
            "startTime": 1430,
            "endTime": 1530,
            "popularity": 100
        }
    ]
}

### POST NULL datas to test for success message

{{httpMethod1}} {{url1}} HTTP/1.1
Content-Type: application/json

{
    "data": []
}

### GET ALL datas to test for success message

{{httpMethod2}} {{url1}} HTTP/1.1
Content-Type: application/json

### GET REQUIRED datas to test for success message

GET http://localhost:3000/advance/result?festivalId=9900000004 HTTP/1.1
Content-Type: application/json  