POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "performanceId": 1234567890,
            "startTime": 1330,
            "endTime": 1530
        },
        {
            "performanceId": 1234567891,
            "startTime": 1330,
            "endTime": 1530
        },
        {
            "performanceId": 1234567892,
            "startTime": 1330,
            "endTime": 1530
        }
    ]
}

###

GET http://localhost:3000/basic/data?festivalId=1234567890&startTime=1330&page=2&pageSize=1 HTTP/1.1
Content-Type: application/json