POST http://localhost:3000/basic/insert HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "performanceId": 1234567890,
            "startTime": 13-30,
            "endTime": 15-30
        },
         {
            "performanceId": 1234567891,
            "startTime": 15-30,
            "endTime": 16-30
        }
    ]
}