-- ATTENTION! THIS SCRIPT IS NOT PART OF THE FILE SYSTEM AND
--      IS PLACED HERE JUST TO FACILITATE THE TEAM FOR CODING 
--      THE SQL QUERIES IN VS CODE.
--      THIS SCRIPT HERE CONTROLS THE 'public' SCHEMAS IN PGADMIN4

-- NOTE! INTEGER CHECK MIGHT NEED TO BE REMOVED BASED ON CIRCUMSTANCE IN FUTURE.

-- Performance 
DROP TABLE IF EXISTS MusicFestival;
DROP TABLE IF EXISTS Performance;
DROP TABLE IF EXISTS PerformanceWithPopularity;
CREATE TABLE Performance(
    performanceId BIGINT PRIMARY KEY NOT NULL CHECK (performanceId BETWEEN 0000000001 and 9999999999) UNIQUE,
    startTime SMALLINT NOT NULL,
    endTime SMALLINT NOT NULL,
    festivalId BIGINT NOT NULL CHECK (festivalId BETWEEN 0000000001 and 9999999999),
    FOREIGN KEY (festivalId) REFERENCES MusicFestival(festivalId)
);

-- Music Festival Table
CREATE TABLE MusicFestival(
    festivalId BIGINT PRIMARY KEY NOT NULL CHECK (festivalId BETWEEN 0000000001 AND 9999999999)
);

-- Performance With Popularity Table
CREATE TABLE PerformanceWithPopularity(
    performanceId BIGINT PRIMARY KEY NOT NULL CHECK (performanceId BETWEEN 0000000001 and 9999999999) UNIQUE,
    startTime SMALLINT NOT NULL,
    endTime SMALLINT NOT NULL,
    festivalId BIGINT NOT NULL CHECK (festivalId BETWEEN 0000000001 and 9999999999),
    popularity NUMERIC NOT NULL,
    FOREIGN KEY (festivalId) REFERENCES MusicFestival(festivalId)
);

SELECT * FROM Performance
SELECT * FROM MusicFestival
SELECT * FROM PerformanceWithPopularity